name: pati_takip
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  image_picker: ^1.0.7
  http: ^1.1.0
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  js: ^0.6.7

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  flutter_tts: ^3.8.5
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.0
  firebase_database: ^11.3.10
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_sound: ^9.28.0
  open_file: ^3.5.10
  permission_handler: ^12.0.1
  path_provider: ^2.1.2
  timezone: ^0.9.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/WhatsApp Görsel 2025-07-24 saat 22.18.58_47c67ca0.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/WhatsApp Görsel 2025-07-24 saat 22.18.58_47c67ca0.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/WhatsApp Görsel 2025-07-24 saat 22.18.58_47c67ca0.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/WhatsApp Görsel 2025-07-24 saat 22.18.58_47c67ca0.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/icon/paw_icon.svg
    - assets/icon/paw_icon.png
  generate: true
  

 